export const COUNTRIES = [
  { countryCode: "AF", country: "Afganistán", flag: "🇦🇫" },
  { countryCode: "AX", country: "Islas Åland", flag: "🇦🇽" },
  { countryCode: "AL", country: "Albania", flag: "🇦🇱" },
  { countryCode: "DZ", country: "Argelia", flag: "🇩🇿" },
  { countryCode: "AS", country: "Samoa Americana", flag: "🇦🇸" },
  { countryCode: "AD", country: "Andorra", flag: "🇦🇩" },
  { countryCode: "AO", country: "Angola", flag: "🇦🇴" },
  { countryCode: "AI", country: "Anguila", flag: "🇦🇮" },
  { countryCode: "AQ", country: "Antártida", flag: "🇦🇶" },
  { countryCode: "AG", country: "Antigua y Barbuda", flag: "🇦🇬" },
  { countryCode: "AR", country: "Argentina", flag: "🇦🇷" },
  { countryCode: "AM", country: "Armenia", flag: "🇦🇲" },
  { countryCode: "AW", country: "Aruba", flag: "🇦🇼" },
  { countryCode: "AU", country: "Australia", flag: "🇦🇺" },
  { countryCode: "AT", country: "Austria", flag: "🇦🇹" },
  { countryCode: "AZ", country: "Azerbaiyán", flag: "🇦🇿" },
  { countryCode: "BS", country: "Bahamas", flag: "🇧🇸" },
  { countryCode: "BH", country: "Baréin", flag: "🇧🇭" },
  { countryCode: "BD", country: "Bangladés", flag: "🇧🇩" },
  { countryCode: "BB", country: "Barbados", flag: "🇧🇧" },
  { countryCode: "BY", country: "Bielorrusia", flag: "🇧🇾" },
  { countryCode: "BE", country: "Bélgica", flag: "🇧🇪" },
  { countryCode: "BZ", country: "Belice", flag: "🇧🇿" },
  { countryCode: "BJ", country: "Benín", flag: "🇧🇯" },
  { countryCode: "BM", country: "Bermudas", flag: "🇧🇲" },
  { countryCode: "BT", country: "Bután", flag: "🇧🇹" },
  { countryCode: "BO", country: "Bolivia", flag: "🇧🇴" },
  { countryCode: "BA", country: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { countryCode: "BW", country: "Botsuana", flag: "🇧🇼" },
  { countryCode: "BV", country: "Isla Bouvet", flag: "🇧🇻" },
  { countryCode: "BR", country: "Brasil", flag: "🇧🇷" },
  { countryCode: "IO", country: "Territorio Británico del Océano Índico", flag: "🇮🇴" },
  { countryCode: "BN", country: "Brunéi", flag: "🇧🇳" },
  { countryCode: "BG", country: "Bulgaria", flag: "🇧🇬" },
  { countryCode: "BF", country: "Burkina Faso", flag: "🇧🇫" },
  { countryCode: "BI", country: "Burundi", flag: "🇧🇮" },
  { countryCode: "KH", country: "Camboya", flag: "🇰🇭" },
  { countryCode: "CM", country: "Camerún", flag: "🇨🇲" },
  { countryCode: "CA", country: "Canadá", flag: "🇨🇦" },
  { countryCode: "CV", country: "Cabo Verde", flag: "🇨🇻" },
  { countryCode: "KY", country: "Islas Caimán", flag: "🇰🇾" },
  { countryCode: "CF", country: "República Centroafricana", flag: "🇨🇫" },
  { countryCode: "TD", country: "Chad", flag: "🇹🇩" },
  { countryCode: "CL", country: "Chile", flag: "🇨🇱" },
  { countryCode: "CN", country: "China", flag: "🇨🇳" },
  { countryCode: "CX", country: "Isla de Navidad", flag: "🇨🇽" },
  { countryCode: "CC", country: "Islas Cocos", flag: "🇨🇨" },
  { countryCode: "CO", country: "Colombia", flag: "🇨🇴" },
  { countryCode: "KM", country: "Comoras", flag: "🇰🇲" },
  { countryCode: "CG", country: "Congo", flag: "🇨🇬" },
  { countryCode: "CD", country: "República Democrática del Congo", flag: "🇨🇩" },
  { countryCode: "CK", country: "Islas Cook", flag: "🇨🇰" },
  { countryCode: "CR", country: "Costa Rica", flag: "🇨🇷" },
  { countryCode: "CI", country: "Costa de Marfil", flag: "🇨🇮" },
  { countryCode: "HR", country: "Croacia", flag: "🇭🇷" },
  { countryCode: "CU", country: "Cuba", flag: "🇨🇺" },
  { countryCode: "CY", country: "Chipre", flag: "🇨🇾" },
  { countryCode: "CZ", country: "República Checa", flag: "🇨🇿" },
  { countryCode: "DK", country: "Dinamarca", flag: "🇩🇰" },
  { countryCode: "DJ", country: "Yibuti", flag: "🇩🇯" },
  { countryCode: "DM", country: "Dominica", flag: "🇩🇲" },
  { countryCode: "DO", country: "República Dominicana", flag: "🇩🇴" },
  { countryCode: "EC", country: "Ecuador", flag: "🇪🇨" },
  { countryCode: "EG", country: "Egipto", flag: "🇪🇬" },
  { countryCode: "SV", country: "El Salvador", flag: "🇸🇻" },
  { countryCode: "GQ", country: "Guinea Ecuatorial", flag: "🇬🇶" },
  { countryCode: "ER", country: "Eritrea", flag: "🇪🇷" },
  { countryCode: "EE", country: "Estonia", flag: "🇪🇪" },
  { countryCode: "SZ", country: "Esuatini", flag: "🇸🇿" },
  { countryCode: "ET", country: "Etiopía", flag: "🇪🇹" },
  { countryCode: "FK", country: "Islas Malvinas", flag: "🇫🇰" },
  { countryCode: "FO", country: "Islas Feroe", flag: "🇫🇴" },
  { countryCode: "FJ", country: "Fiyi", flag: "🇫🇯" },
  { countryCode: "FI", country: "Finlandia", flag: "🇫🇮" },
  { countryCode: "FR", country: "Francia", flag: "🇫🇷" },
  { countryCode: "GF", country: "Guayana Francesa", flag: "🇬🇫" },
  { countryCode: "PF", country: "Polinesia Francesa", flag: "🇵🇫" },
  { countryCode: "TF", country: "Territorios Australes Franceses", flag: "🇹🇫" },
  { countryCode: "GA", country: "Gabón", flag: "🇬🇦" },
  { countryCode: "GM", country: "Gambia", flag: "🇬🇲" },
  { countryCode: "GE", country: "Georgia", flag: "🇬🇪" },
  { countryCode: "DE", country: "Alemania", flag: "🇩🇪" },
  { countryCode: "GH", country: "Ghana", flag: "🇬🇭" },
  { countryCode: "GI", country: "Gibraltar", flag: "🇬🇮" },
  { countryCode: "GR", country: "Grecia", flag: "🇬🇷" },
  { countryCode: "GL", country: "Groenlandia", flag: "🇬🇱" },
  { countryCode: "GD", country: "Granada", flag: "🇬🇩" },
  { countryCode: "GP", country: "Guadalupe", flag: "🇬🇵" },
  { countryCode: "GU", country: "Guam", flag: "🇬🇺" },
  { countryCode: "GT", country: "Guatemala", flag: "🇬🇹" },
  { countryCode: "GG", country: "Guernsey", flag: "🇬🇬" },
  { countryCode: "GN", country: "Guinea", flag: "🇬🇳" },
  { countryCode: "GW", country: "Guinea-Bisáu", flag: "🇬🇼" },
  { countryCode: "GY", country: "Guyana", flag: "🇬🇾" },
  { countryCode: "HT", country: "Haití", flag: "🇭🇹" },
  { countryCode: "HM", country: "Islas Heard y McDonald", flag: "🇭🇲" },
  { countryCode: "VA", country: "Ciudad del Vaticano", flag: "🇻🇦" },
  { countryCode: "HN", country: "Honduras", flag: "🇭🇳" },
  { countryCode: "HK", country: "Hong Kong", flag: "🇭🇰" },
  { countryCode: "HU", country: "Hungría", flag: "🇭🇺" },
  { countryCode: "IS", country: "Islandia", flag: "🇮🇸" },
  { countryCode: "IN", country: "India", flag: "🇮🇳" },
  { countryCode: "ID", country: "Indonesia", flag: "🇮🇩" },
  { countryCode: "IR", country: "Irán", flag: "🇮🇷" },
  { countryCode: "IQ", country: "Irak", flag: "🇮🇶" },
  { countryCode: "IE", country: "Irlanda", flag: "🇮🇪" },
  { countryCode: "IM", country: "Isla de Man", flag: "🇮🇲" },
  { countryCode: "IL", country: "Israel", flag: "🇮🇱" },
  { countryCode: "IT", country: "Italia", flag: "🇮🇹" },
  { countryCode: "JM", country: "Jamaica", flag: "🇯🇲" },
  { countryCode: "JP", country: "Japón", flag: "🇯🇵" },
  { countryCode: "JE", country: "Jersey", flag: "🇯🇪" },
  { countryCode: "JO", country: "Jordania", flag: "🇯🇴" },
  { countryCode: "KZ", country: "Kazajistán", flag: "🇰🇿" },
  { countryCode: "KE", country: "Kenia", flag: "🇰🇪" },
  { countryCode: "KI", country: "Kiribati", flag: "🇰🇮" },
  { countryCode: "KP", country: "Corea del Norte", flag: "🇰🇵" },
  { countryCode: "KR", country: "Corea del Sur", flag: "🇰🇷" },
  { countryCode: "KW", country: "Kuwait", flag: "🇰🇼" },
  { countryCode: "KG", country: "Kirguistán", flag: "🇰🇬" },
  { countryCode: "LA", country: "Laos", flag: "🇱🇦" },
  { countryCode: "LV", country: "Letonia", flag: "🇱🇻" },
  { countryCode: "LB", country: "Líbano", flag: "🇱🇧" },
  { countryCode: "LS", country: "Lesoto", flag: "🇱🇸" },
  { countryCode: "LR", country: "Liberia", flag: "🇱🇷" },
  { countryCode: "LY", country: "Libia", flag: "🇱🇾" },
  { countryCode: "LI", country: "Liechtenstein", flag: "🇱🇮" },
  { countryCode: "LT", country: "Lituania", flag: "🇱🇹" },
  { countryCode: "LU", country: "Luxemburgo", flag: "🇱🇺" },
  { countryCode: "MO", country: "Macao", flag: "🇲🇴" },
  { countryCode: "MG", country: "Madagascar", flag: "🇲🇬" },
  { countryCode: "MW", country: "Malaui", flag: "🇲🇼" },
  { countryCode: "MY", country: "Malasia", flag: "🇲🇾" },
  { countryCode: "MV", country: "Maldivas", flag: "🇲🇻" },
  { countryCode: "ML", country: "Malí", flag: "🇲🇱" },
  { countryCode: "MT", country: "Malta", flag: "🇲🇹" },
  { countryCode: "MH", country: "Islas Marshall", flag: "🇲🇭" },
  { countryCode: "MQ", country: "Martinica", flag: "🇲🇶" },
  { countryCode: "MR", country: "Mauritania", flag: "🇲🇷" },
  { countryCode: "MU", country: "Mauricio", flag: "🇲🇺" },
  { countryCode: "YT", country: "Mayotte", flag: "🇾🇹" },
  { countryCode: "MX", country: "México", flag: "🇲🇽" },
  { countryCode: "FM", country: "Micronesia", flag: "🇫🇲" },
  { countryCode: "MD", country: "Moldavia", flag: "🇲🇩" },
  { countryCode: "MC", country: "Mónaco", flag: "🇲🇨" },
  { countryCode: "MN", country: "Mongolia", flag: "🇲🇳" },
  { countryCode: "ME", country: "Montenegro", flag: "🇲🇪" },
  { countryCode: "MS", country: "Montserrat", flag: "🇲🇸" },
  { countryCode: "MA", country: "Marruecos", flag: "🇲🇦" },
  { countryCode: "MZ", country: "Mozambique", flag: "🇲🇿" },
  { countryCode: "MM", country: "Myanmar", flag: "🇲🇲" },
  { countryCode: "NA", country: "Namibia", flag: "🇳🇦" },
  { countryCode: "NR", country: "Nauru", flag: "🇳🇷" },
  { countryCode: "NP", country: "Nepal", flag: "🇳🇵" },
  { countryCode: "NL", country: "Países Bajos", flag: "🇳🇱" },
  { countryCode: "NC", country: "Nueva Caledonia", flag: "🇳🇨" },
  { countryCode: "NZ", country: "Nueva Zelanda", flag: "🇳🇿" },
  { countryCode: "NI", country: "Nicaragua", flag: "🇳🇮" },
  { countryCode: "NE", country: "Níger", flag: "🇳🇪" },
  { countryCode: "NG", country: "Nigeria", flag: "🇳🇬" },
  { countryCode: "NU", country: "Niue", flag: "🇳🇺" },
  { countryCode: "NF", country: "Isla Norfolk", flag: "🇳🇫" },
  { countryCode: "MK", country: "Macedonia del Norte", flag: "🇲🇰" },
  { countryCode: "MP", country: "Islas Marianas del Norte", flag: "🇲🇵" },
  { countryCode: "NO", country: "Noruega", flag: "🇳🇴" },
  { countryCode: "OM", country: "Omán", flag: "🇴🇲" },
  { countryCode: "PK", country: "Pakistán", flag: "🇵🇰" },
  { countryCode: "PW", country: "Palaos", flag: "🇵🇼" },
  { countryCode: "PS", country: "Palestina", flag: "🇵🇸" },
  { countryCode: "PA", country: "Panamá", flag: "🇵🇦" },
  { countryCode: "PG", country: "Papúa Nueva Guinea", flag: "🇵🇬" },
  { countryCode: "PY", country: "Paraguay", flag: "🇵🇾" },
  { countryCode: "PE", country: "Perú", flag: "🇵🇪" },
  { countryCode: "PH", country: "Filipinas", flag: "🇵🇭" },
  { countryCode: "PN", country: "Islas Pitcairn", flag: "🇵🇳" },
  { countryCode: "PL", country: "Polonia", flag: "🇵🇱" },
  { countryCode: "PT", country: "Portugal", flag: "🇵🇹" },
  { countryCode: "PR", country: "Puerto Rico", flag: "🇵🇷" },
  { countryCode: "QA", country: "Catar", flag: "🇶🇦" },
  { countryCode: "RE", country: "Reunión", flag: "🇷🇪" },
  { countryCode: "RO", country: "Rumanía", flag: "🇷🇴" },
  { countryCode: "RU", country: "Rusia", flag: "🇷🇺" },
  { countryCode: "RW", country: "Ruanda", flag: "🇷🇼" },
  { countryCode: "BL", country: "San Bartolomé", flag: "🇧🇱" },
  { countryCode: "SH", country: "Santa Elena", flag: "🇸🇭" },
  { countryCode: "KN", country: "San Cristóbal y Nieves", flag: "🇰🇳" },
  { countryCode: "LC", country: "Santa Lucía", flag: "🇱🇨" },
  { countryCode: "MF", country: "San Martín", flag: "🇲🇫" },
  { countryCode: "PM", country: "San Pedro y Miquelón", flag: "🇵🇲" },
  { countryCode: "VC", country: "San Vicente y las Granadinas", flag: "🇻🇨" },
  { countryCode: "WS", country: "Samoa", flag: "🇼🇸" },
  { countryCode: "SM", country: "San Marino", flag: "🇸🇲" },
  { countryCode: "ST", country: "Santo Tomé y Príncipe", flag: "🇸🇹" },
  { countryCode: "SA", country: "Arabia Saudita", flag: "🇸🇦" },
  { countryCode: "SN", country: "Senegal", flag: "🇸🇳" },
  { countryCode: "RS", country: "Serbia", flag: "🇷🇸" },
  { countryCode: "SC", country: "Seychelles", flag: "🇸🇨" },
  { countryCode: "SL", country: "Sierra Leona", flag: "🇸🇱" },
  { countryCode: "SG", country: "Singapur", flag: "🇸🇬" },
  { countryCode: "SK", country: "Eslovaquia", flag: "🇸🇰" },
  { countryCode: "SI", country: "Eslovenia", flag: "🇸🇮" },
  { countryCode: "SB", country: "Islas Salomón", flag: "🇸🇧" },
  { countryCode: "SO", country: "Somalia", flag: "🇸🇴" },
  { countryCode: "ZA", country: "Sudáfrica", flag: "🇿🇦" },
  { countryCode: "GS", country: "Islas Georgias del Sur y Sandwich del Sur", flag: "🇬🇸" },
  { countryCode: "SS", country: "Sudán del Sur", flag: "🇸🇸" },
  { countryCode: "ES", country: "España", flag: "🇪🇸" },
  { countryCode: "LK", country: "Sri Lanka", flag: "🇱🇰" },
  { countryCode: "SD", country: "Sudán", flag: "🇸🇩" },
  { countryCode: "SR", country: "Surinam", flag: "🇸🇷" },
  { countryCode: "SJ", country: "Svalbard y Jan Mayen", flag: "🇸🇯" },
  { countryCode: "SE", country: "Suecia", flag: "🇸🇪" },
  { countryCode: "CH", country: "Suiza", flag: "🇨🇭" },
  { countryCode: "SY", country: "Siria", flag: "🇸🇾" },
  { countryCode: "TW", country: "Taiwán", flag: "🇹🇼" },
  { countryCode: "TJ", country: "Tayikistán", flag: "🇹🇯" },
  { countryCode: "TZ", country: "Tanzania", flag: "🇹🇿" },
  { countryCode: "TH", country: "Tailandia", flag: "🇹🇭" },
  { countryCode: "TL", country: "Timor Oriental", flag: "🇹🇱" },
  { countryCode: "TG", country: "Togo", flag: "🇹🇬" },
  { countryCode: "TK", country: "Tokelau", flag: "🇹🇰" },
  { countryCode: "TO", country: "Tonga", flag: "🇹🇴" },
  { countryCode: "TT", country: "Trinidad y Tobago", flag: "🇹🇹" },
  { countryCode: "TN", country: "Túnez", flag: "🇹🇳" },
  { countryCode: "TR", country: "Turquía", flag: "🇹🇷" },
  { countryCode: "TM", country: "Turkmenistán", flag: "🇹🇲" },
  { countryCode: "TC", country: "Islas Turcas y Caicos", flag: "🇹🇨" },
  { countryCode: "TV", country: "Tuvalu", flag: "🇹🇻" },
  { countryCode: "UG", country: "Uganda", flag: "🇺🇬" },
  { countryCode: "UA", country: "Ucrania", flag: "🇺🇦" },
  { countryCode: "AE", country: "Emiratos Árabes Unidos", flag: "🇦🇪" },
  { countryCode: "GB", country: "Reino Unido", flag: "🇬🇧" },
  { countryCode: "US", country: "Estados Unidos", flag: "🇺🇸" },
  { countryCode: "UM", country: "Islas Ultramarinas Menores de Estados Unidos", flag: "🇺🇸" },
  { countryCode: "UY", country: "Uruguay", flag: "🇺🇾" },
  { countryCode: "UZ", country: "Uzbekistán", flag: "🇺🇿" },
  { countryCode: "VU", country: "Vanuatu", flag: "🇻🇺" },
  { countryCode: "VE", country: "Venezuela", flag: "🇻🇪" },
  { countryCode: "VN", country: "Vietnam", flag: "🇻🇳" },
  { countryCode: "VG", country: "Islas Vírgenes Británicas", flag: "🇻🇬" },
  { countryCode: "VI", country: "Islas Vírgenes de los Estados Unidos", flag: "🇻🇮" },
  { countryCode: "WF", country: "Wallis y Futuna", flag: "🇼🇫" },
  { countryCode: "EH", country: "Sahara Occidental", flag: "🇪🇭" },
  { countryCode: "YE", country: "Yemen", flag: "🇾🇪" },
  { countryCode: "ZM", country: "Zambia", flag: "🇿🇲" },
  { countryCode: "ZW", country: "Zimbabue", flag: "🇿🇼" }
] as const;

export type CountryCode = typeof COUNTRIES[number]['countryCode']; 